# Generated by Django 5.1.7 on 2025-05-30 12:57

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default=1, max_length=100, unique=True)),
                ('email', models.EmailField(default='puku.chome0603@gmail.com', max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarTaskModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('title_reason', models.CharField(max_length=100, null=True)),
                ('achievement_title', models.CharField(max_length=100, null=True)),
                ('when_if', models.CharField(max_length=100, null=True)),
                ('when_then', models.CharField(max_length=100, null=True)),
                ('obstacle_if', models.CharField(max_length=100, null=True)),
                ('obstacle_then', models.CharField(max_length=100, null=True)),
                ('backgroundColor', models.CharField(choices=[('#696969', 'Planned_color'), ('#c11336', 'Done_color'), ('#0000cd', 'Failed_color')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Done', 'Done'), ('Failed', 'Failed')], max_length=7, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('allDay', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taskmodel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('title_reason', models.CharField(max_length=100, null=True)),
                ('achievement_title', models.CharField(max_length=100, null=True)),
                ('when_if', models.CharField(max_length=100, null=True)),
                ('when_then', models.CharField(max_length=100, null=True)),
                ('obstacle_if', models.CharField(max_length=100, null=True)),
                ('obstacle_then', models.CharField(max_length=100, null=True)),
                ('backgroundColor', models.CharField(choices=[('#696969', 'Planned_color'), ('#c11336', 'Done_color'), ('#0000cd', 'Failed_color')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Done', 'Done'), ('Failed', 'Failed')], max_length=7, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('allDay', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
