# Generated by Django 5.1.7 on 2025-05-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendartaskmodel',
            options={'verbose_name': 'CalendarTaskModel'},
        ),
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': 'TaskModel'},
        ),
        migrations.RemoveField(
            model_name='calendartaskmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='calendartasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.calendartaskmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.taskmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='h.hatori0603@gmail.com', max_length=254, unique=True),
        ),
    ]
